server {
    listen 80;
    root /var/www/html;
    index index.php index.html;
    error_page 401 /status-codes/401.html;
    error_page 404 /status-codes/404.html;
    error_page 403 /status-codes/404.html;

    # This project is not a good example but it's best practice
    # to place backend directly outside the root.
    # However if you don't, it is important to add this:
    location ~ ^/(config|models)/ {
        return 404;
    }

    location / {
        try_files $uri $uri/ = 404;
    }

    location ~ \.php$ {
        fastcgi_pass php:9000;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }
}
